### ISSUE TITLE
Regression: deadlock in file handling

### ISSUE THREAD

**Issue by ffrank** [purpleidea/mgmt#76] opened 2016-09-28 22:22 UTC
`mgmt` can get stuck managing a file resource.

How to reproduce:

1. Run the file1 example

        mkdir /tmp/mgmt
        mgmt run --tmp-prefix --file examples/file1.yaml

2. Remove `/tmp/mgmt/f3`

3. Try and `Ctrl-C` out of `mgmt`.

It does work if all files existed anyway. In this case, removing `f3` twice in a row will cause the lock-up. (Or something along those lines.)

```
VERSION:
   0.0.4-30-g9368c7e

$ git submodule status
 e2d51961dd4abe6540c7d8e4aac0da7addf2e16e vendor/github.com/coreos/etcd (v3.1.0-alpha.1-13-ge2d5196)
 acebe0f9ff5993e130b141ee60e83e592839ca22 vendor/github.com/grpc-ecosystem/grpc-gateway (v1.1.0-13-gacebe0f)
 231b4cfea0e79843053a33f5fe90bd4d84b23cd3 vendor/google.golang.org/grpc (v1.0.0-183-g231b4cf)
 7be54206639f256967dd82fa767397ba5f8f48f5 vendor/gopkg.in/fsnotify.v1 (v1.2.1)
```

**Comment by purpleidea** [comment] 2016-09-28 22:32
I did indeed think this got fixed with: https://github.com/purpleidea/mgmt/commit/654b3e9dbe62c18d8bdcc0e4ee6855396da37986

Maybe I was wrong. It was indeed a serious issue, but I am convinced it's due to the fsnotify lib.

@ffrank Do you feel like doing a git bisect on the fsnotify lib, skipping commits that don't compile? If not I can do this after some of the conference meetings die down.

**Comment by ffrank** [comment] 2016-09-28 22:55
I'll try some older `fsnotify` versions, sure.

**Comment by ffrank** [comment] 2016-09-28 23:14
Current vendor version is `1.2.1`. I reproduce the issue with `1.2.0`.

`1.1.x` does not seem to work at all. I get these errors:
```
01:07:45 pgraph.go:842: File[file3]: Watch errored: Unknown File[file3] error: inotify_add_watch: no such file or directory
01:07:45 pgraph.go:881: File[file3]: Exited with failure: Permanent watch error: Unknown File[file3] error: inotify_add_watch: no such file or directory
...
01:07:45 pgraph.go:842: File[file4]: Watch errored: Unknown File[file4] error: inotify_add_watch: no such file or directory
01:07:45 pgraph.go:881: File[file4]: Exited with failure: Permanent watch error: Unknown File[file4] error: inotify_add_watch: no such file or directory
```

I'll do some digging in our (downstream) history now, see if I can find a point at which it still worked.

**Comment by ffrank** [comment] 2016-09-28 23:35
Success! The `0.0.4` release version still works. Here's the bisect result:
```
53cabd5ee49e57f6b7ae82c66948bebff17deef3 is the first bad commit
commit 53cabd5ee49e57f6b7ae82c66948bebff17deef3
Author: James Shubin <james@shubin.ca>
Date:   Wed Sep 14 04:33:03 2016 -0400

    Resources: Prototype retry and retry delay meta parameters
```
If I feel like it tomorrow (and if you aren't faster), I may just try and find the issue.

**Comment by purpleidea** [comment] 2016-09-29 07:00
@ffrank Hmmm Really?
I actually meant bisect based on fsnotify, but I'll look at that too.
It is both things?

**Comment by ffrank** [comment] 2016-09-29 11:19
My previous comment indicates the point of breakage, which is definitely within `mgmt`. Sorry man.

The [comment before that](https://github.com/purpleidea/mgmt/issues/76#issuecomment-250328744) describes why bisecting `fsnotify` is not an option: There is no older version of it that makes `mgmt` work (which makes sense, as the error appeared in `mgmt`). I did not check if *newer* `fsnotify` versions fix the bug, because that seemed nonsensical to me - you had just vendored that specific version, so I assume there is some definite breakage beyond it that keeps us from tracking master.

**Comment by purpleidea** [comment] 2016-09-29 11:23
Sorry is not needed. If I broke it, I'll fix it :)
Will hack on this later!

**Comment by purpleidea** [comment] 2016-10-01 12:23
This should now be fixed in https://github.com/purpleidea/mgmt/commit/567dcaf79db4683fba80f50efba224dba7c43d8f

I think this issue was tricky because the deadlocks we were seeing were due to TWO different reasons. This one *and* the previously patched fsnotify regression (solved with vendoring).

Hopefully there isn't a third one lurking! If this doesn't fix the issue for you, LMK and I'll reopen.

**Closed by purpleidea** 2016-10-01 12:23 UTC
Labels: bug
