### ISSUE TITLE
provide binaries

### ISSUE THREAD

**Issue by roidelapluie** [purpleidea/mgmt#186] opened 2017-03-16 14:00 UTC
When we release mgmt we should also publish binaries.

**Comment by purpleidea** [comment] 2017-03-16 14:02
Agreed. RPM/Deb or also plain binaries?

**Comment by purpleidea** [comment] 2017-03-16 14:02
BTW, this was already mentioned in https://github.com/purpleidea/mgmt/issues/113 so closing as a dupe of that bug.

**Closed by purpleidea** 2017-03-16 14:02 UTC
